### PR TITLE
Add SSLPolicy class that will use chefdk trusted certs path

### LINKED ISSUE #1470: Recognize certificates from ChefDK trusted_certs path
This would be helpful as I've ran into issues when using a private supermarket to download cookbooks from it without disabling SSL.

With knife I can simply run `knife ssl fetch` and my knife commands will work properly with my supermarket server.  However Berkshelf continues to not work.

It was mentioned in https://github.com/chef/chef-dk/issues/514 that I could try opening an issue here to have Berkshelf recognize certificates that are in `~/.chef/trusted_certs` which is where `knife ssl fetch` puts certificates.

### PR DESCRIPTION
**Pull request by afiune**
We are introducing a new class called `SSLPolicy` that, by default, will create the SSL Store pointing to the chef trusted certificates path. The class has been implemented in the main `Uploader` and `Downloader` so that they now pass an extra SSL option called `cert_store`. This options are passed to the underlayer gem `Ridley` that itself passes them to `Faraday` (HTTP client) so that on every connection we use the SSL store we provided for authentication. :mindblown:

Fixes #1470

### CODE REVIEW

**Comment by afiune** [comment]
ping @howdoicomputer @srenatus !! 

Gotta open a new PR but look at this, tests passed!!

**Comment by afiune** [comment]
cc/ @berkshelf/berks-core

**Comment by howdoicomputer** [comment]
huzzah

**Comment by afiune** [comment]
Looking more in detail I really don't see how this is going to work. 😂 At the end of the day we need Ridley to understand the trusted_cert_dir and I don't think we do that there. I might look closer at this tomorrow morning.

**Comment by afiune** [comment]
This commit will fail on the tests intentionally so we have time to make some analysis on the missing parts of the puzzle. 

Im putting this on hold for a moment since we have some other priorities with ChefDK release. 

I'll come back soon though!

**Comment by afiune** [comment]
Alright Im back to work on this!! 👍

**Comment by afiune** [comment]
If someone looks like this after reading through this PR; **I will understand...**

**Comment by afiune** [comment]
cc/ @berkshelf/berks-core

**Comment by danielsdeleo** [comment]
This looks good to me. If you wanted to go a step further, you could move some of the code into `chef-config` so berks and knife will have identical behavior and bug fixes. But this is already a big improvement so that could be saved for the future.

**Comment by howdoicomputer** [comment]
Oh, yeah, this thing.

**Comment by lamont-granquist** [comment]
👍

**Comment by afiune** [comment]
I am approving this since we have two +1

@danielsdeleo I am creating an issue to go the extra mile on a different card. It is indeed a great idea that we would love to implement on the next iteration. 💯

**Comment by howdoicomputer** [comment]
Ahhhh code I wrote ended up in berkshellf :smile: I can look into that additional ticket.

**Comment by vinyar** [comment]
Ok, so I wanted to make sure the code in this PR handles a particular usecase:

Chef server is using a cert issued by company's internal CA. All of their machines come with a CA built-in, so all chef-clients run succeed without the need to have full cert chain in trusted_certs folder.

If Berks only knows about the trusted_cert folder, it may still fail, because root CA is in a different store.

**Pull request merged**
