### PR TITLE
berks apply env file option

### PR DESCRIPTION
**Pull request by phoolish**
Pass berkshelf an environment file path to update during apply.

### CODE REVIEW

**Comment by reset** [comment]
@phoolish sorry for such a late follow up on this. I'm all for this feature, but each time somebody has requested this it has sounded like an "either/or" type of thing.

I think we should make the `name` argument optional in Thor, but do manual checking to see if it or the `-f` flag is present. If the `-f` flag is present we continue and *do not* attempt to update the Chef Server, instead we just update the contents at the given filepath. If the `-f` flag is not provided, then we should ensure a value for the `name` argument was provided and continue as normal.

If you wanna make those changes and push them back to this PR I'll merge it in!

Implements #875

**Comment by louis-gounot** [comment]
@reset : Basically, you want the remote apply (on Chef server) to be done only if -f (env file) is not provided and the environement file to be handled only if -f is provided. Am I right ?
Unit tests must also be updated by the way.
Will try to handle this if you confirm by the end of the week (really want this feature :wink)

**Comment by reset** [comment]
@louis-gounot yup, that's what I'm looking for!

**Comment by louis-gounot** [comment]
@reset : created #1512 for exclusive mode implementation.

**Comment by reset** [comment]
Closing via https://github.com/berkshelf/berkshelf/pull/1512

**Comment by phoolish** [comment]
@louis-gounot @reset I've been out on vacation.  Thanks for handling this!  Looking forward to using the functionality.

**Pull request closed without merging**
