### PR TITLE
allow user to change git url handler

### PR DESCRIPTION
**Pull request by kernelsmith**
This PR addresses #1503 and allows the user to select what transport protocol a github directive in a Berksfile uses.  In many environments the clear-text git protocol is blocked (port 9418), so if a Berksfile has indicated github: 'some/repo' at any point, a user is going to have to fork and maintain their own version so they can switch to the long form git: option to utilize ssh or https. This PR makes the protocol  dynamic via the github.protocol item in the config file.  Supported protocols are :git (default), :ssh, and :https

### CODE REVIEW

**Comment by thommay** [comment]
Hi, I think this is goodness. I'd like to see the default be `https`, though. Other than that it just needs a rebase and we'll get it merged, if you'd be ok to do that?

**Comment by kernelsmith** [comment]
I'll try rebasing, but it won't be for a lil while, having back fused tomorrow

**Comment by thommay** [comment]
@kernelsmith oh, don't worry - we did this for you in #1585 . Hope the surgery goes well!

**Comment by kernelsmith** [comment]
Cheers! 
yeah_f_yeah

**Pull request closed without merging**
