### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by danielsdeleo**

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Upstream fix for the grape issue is here: https://github.com/berkshelf/berkshelf-api/pull/211

**Comment by jkeiser** [comment]
:+1:

**Comment by danielsdeleo** [comment]
Ugh, the travis issues are this: `undefined method `size' for #<Bundler::SpecSet:0x00000001b759e8>`

This is an issue that I reported and has since been fixed in bundler (https://github.com/bundler/bundler/issues/4368). What's the best way past this for now? We have to either monkey-patch bundler, as in https://github.com/chef/chef-dk/commit/138e512144adbfcba7dea3db5448afdd539a89f1 or change travis so it only upgrades RubyGems to 2.6.1 (I think). Preferences?

@reset ?

**Comment by reset** [comment]
@danielsdeleo probably update Travis to avoid the overhead of a monkey patch

**Comment by danielsdeleo** [comment]
@reset look good? I'd like to do a 4.3.1 release with this.  The goal is to get ChefDK building a version of berks that pins libgecode to 1.2.0, otherwise we are making packages with two libgecodes.

**Comment by reset** [comment]
@danielsdeleo for sure, let it rip!

**Pull request merged**
