### PR TITLE
Make vagrant.vm.box and ssl.verify not be required.

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by lamont-granquist** [comment]
so is this just masking that something deeper is broken though?

like was the default satisfying the required line before, and now the default is not being applied so the required is failing, in which case we really need to fix the defaults?

**Comment by lamont-granquist** [comment]
Yeah:

```
     Berkshelf::InvalidConfiguration:
       Invalid configuration:
         vagrant.vm.box Expected attribute: 'vagrant.vm.box' to be a type of: 'String'
         vagrant.vm.box A value is required for attribute: 'vagrant.vm.box'
```

How do we wind up there when there's a default value that should get rendered for vagrant.vm.box?

**Comment by lamont-granquist** [comment]
and how is master of berkshelf passing?

i'm kind of suspicious that you're pulling in an old buff-config or underlying buff-* gem into chef-dk and that this bug has been fixed in berkshelf, but chef-dk isn't properly up to date?  (assuming that this is the berks tests that are failing and not some additional chef-dk testing of berks going on for some reason, i don't have the context on the failure...  i'm assuming this is just chef-dk's validation step that fires off all the specs of all the underlying projects...)

**Comment by jkeiser** [comment]
@lamont-granquist's point that this is the only current test coverage of whatever this issue is is well taken. Closing this until it becomes important to investigate.

**Pull request closed without merging**
