### PR TITLE
Address hashie warning spam

### PR DESCRIPTION
**Pull request by lamont-granquist**
Bit of a hack.

Long term solution would probably be to remove buff-config/varia_model and the hashie dep in favor of Chef::Config and Chef::Mash objects.

### CODE REVIEW

**Comment by shortdudey123** [comment]
Fixes the berkshelf side (https://github.com/berkshelf/berkshelf/issues/1665) of https://github.com/berkshelf/ridley/issues/366

**Comment by rylectro** [comment]
Didn't fix.

$ chef -v                                               
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-03-23T16:48:11.138348 42364] 2017-03-23T16:48:11.138514 42364] 2017-03-23T16:48:11.138634 42364] 2017-03-23T16:48:11.138743 42364] 2017-03-23T16:48:11.211401 42364] 2017-03-23T16:48:11.211546 42364] 5.6.0
kitchen version: 1.15.0

Had to run 
sudo chef gem install berkshelf --install-dir /opt/chefdk/embedded/lib/ruby/gems/2.3.0 --no-user-install --bindir /opt/chefdk/bin/

**Comment by digital-samurai** [comment]
I am on chefdk 1.2.22 installed on windows and am still seeing this even with the hashie settings in this.

**Comment by thommay** [comment]
Please upgrade to 1.3.40 which fixes this.

**Pull request merged**
